import { UserProfile, SectionMeta, DateCategory } from '../types/questionnaire';

export const STORAGE_KEY = 'girlfriend_profile_v1';

export const QUESTIONNAIRE_SECTIONS: SectionMeta[] = [
  {
    id: 'basic',
    stepNumber: 1,
    title: 'A Little About You 🌸',
    shortTitle: 'About You',
    emoji: '🌸',
    subtitle: 'The essential things that make up your beautiful world.',
  },
  {
    id: 'food',
    stepNumber: 2,
    title: 'The Way To Your Heart Might Be Through Food 😋',
    shortTitle: 'Favorite Foods',
    emoji: '😋',
    subtitle: 'So I always know what treats to bring you and where to take you.',
  },
  {
    id: 'habits',
    stepNumber: 3,
    title: 'Understanding Your Little Habits 🌷',
    shortTitle: 'Daily Habits',
    emoji: '🌷',
    subtitle: 'The rhythm of your days, what calms you, and how you recharge.',
  },
  {
    id: 'love',
    stepNumber: 4,
    title: 'How Do You Like To Be Loved? ❤️',
    shortTitle: 'Love & Care',
    emoji: '❤️',
    subtitle: '“I’m asking because I want to love you in the way YOU understand love.”',
  },
  {
    id: 'dates',
    stepNumber: 5,
    title: 'Dates I Never Want To Forget 🗓️',
    shortTitle: 'Important Dates',
    emoji: '🗓️',
    subtitle: 'Milestones, birthdays, and memories etched in our timeline.',
  },
  {
    id: 'likes',
    stepNumber: 6,
    title: 'Likes & Dislikes 💗',
    shortTitle: 'Likes & Dislikes',
    emoji: '💗',
    subtitle: 'Your favorite entertainment, hobbies, and the things to steer clear of.',
  },
  {
    id: 'dreams',
    stepNumber: 7,
    title: 'Your Dreams Matter To Me 🌙',
    shortTitle: 'Her Dreams',
    emoji: '🌙',
    subtitle: 'Your biggest aspirations, travels, and wishes under the stars.',
  },
  {
    id: 'about',
    stepNumber: 8,
    title: 'A Little About Us ❤️',
    shortTitle: 'About Us',
    emoji: '💕',
    subtitle: 'Our shared stories, memories, and the sweet future we look forward to.',
  },
  {
    id: 'rapid',
    stepNumber: 9,
    title: 'Rapid-Fire Round ⚡',
    shortTitle: 'Rapid Fire',
    emoji: '⚡',
    subtitle: 'Quick instincts! Pick whichever speaks to your soul right now.',
  },
];

export const DATE_CATEGORIES: { label: DateCategory; color: string }[] = [
  { label: 'Birthday 🎂', color: 'bg-pink-100 text-pink-700 border-pink-200' },
  { label: 'Anniversary ❤️', color: 'bg-rose-100 text-rose-700 border-rose-200' },
  { label: 'Family 👨‍👩‍👧‍👦', color: 'bg-amber-100 text-amber-700 border-amber-200' },
  { label: 'Friendship 🫶', color: 'bg-purple-100 text-purple-700 border-purple-200' },
  { label: 'College 🎓', color: 'bg-blue-100 text-blue-700 border-blue-200' },
  { label: 'Personal 🌸', color: 'bg-emerald-100 text-emerald-700 border-emerald-200' },
  { label: 'Other ⭐', color: 'bg-indigo-100 text-indigo-700 border-indigo-200' },
];

export const WHEN_UPSET_OPTIONS = [
  'Give me space',
  'Give me a hug',
  'Listen to me',
  'Reassure me',
  'Talk it through with me',
];

export const MAKES_FEEL_LOVED_OPTIONS = [
  'Quality Time ❤️',
  'Words of Affirmation 💬',
  'Gifts 🎁',
  'Acts of Service 🫶',
  'Physical Affection 🤗',
];

export const RAPID_FIRE_QUESTIONS = [
  {
    id: 'teaOrCoffee',
    title: 'Warm Brew',
    optionA: 'Tea ☕',
    optionB: 'Coffee ☕',
    subA: 'Warm, cozy & comforting',
    subB: 'Bold, rich & energizing',
  },
  {
    id: 'callOrText',
    title: 'Staying In Touch',
    optionA: 'Call 📞',
    optionB: 'Text 💬',
    subA: 'Hearing your voice',
    subB: 'Thoughtful messages throughout',
  },
  {
    id: 'beachOrMountains',
    title: 'Getaway Destination',
    optionA: 'Beach 🏖️',
    optionB: 'Mountains 🏔️',
    subA: 'Sun, sand & gentle waves',
    subB: 'Cool mist, pine trees & quiet vistas',
  },
  {
    id: 'sunriseOrSunset',
    title: 'Golden Hour',
    optionA: 'Sunrise 🌅',
    optionB: 'Sunset 🌇',
    subA: 'Fresh morning serenity',
    subB: 'Dreamy twilight dusk',
  },
  {
    id: 'sweetOrSpicy',
    title: 'Flavor Preference',
    optionA: 'Sweet 🍫',
    optionB: 'Spicy 🌶️',
    subA: 'Chocolates & sweet cravings',
    subB: 'Zesty, bold & fiery flavor',
  },
  {
    id: 'movieOrSeries',
    title: 'Watch Preference',
    optionA: 'Movie 🎬',
    optionB: 'Series 📺',
    subA: 'A tight two-hour cinematic date',
    subB: 'A bingeable episodic world',
  },
  {
    id: 'stayHomeOrGoOut',
    title: 'Weekend Mood',
    optionA: 'Stay Home 🏠',
    optionB: 'Go Out 🌃',
    subA: 'Blankets, snacks & cozy vibes',
    subB: 'Exploring cafes & late evening lights',
  },
  {
    id: 'longDriveOrLongWalk',
    title: 'Travel Pace',
    optionA: 'Long Drive 🚗',
    optionB: 'Long Walk 🚶‍♀️',
    subA: 'Windows down, music on replay',
    subB: 'Holding hands, strolling peacefully',
  },
  {
    id: 'giftsOrQualityTime',
    title: 'Heartfelt Connection',
    optionA: 'Gifts 🎁',
    optionB: 'Quality Time ❤️',
    subA: 'Thoughtful tokens of love',
    subB: 'Undivided presence together',
  },
] as const;

export const INITIAL_EMPTY_PROFILE: UserProfile = {
  basicDetails: {
    callName: '',
    nickname: '',
    favoriteColor: '',
    favoriteFlower: '',
    favoriteAnimal: '',
    favoriteSeason: '',
    favoritePlace: '',
    instantHappy: '',
  },
  foodPreferences: {
    favoriteFood: '',
    favoriteIndianFood: '',
    favoriteSouthIndianFood: '',
    favoriteSnack: '',
    favoriteChocolate: '',
    favoriteIceCream: '',
    favoriteFruit: '',
    favoriteDrink: '',
    favoriteFastFood: '',
    favoriteRestaurant: '',
    favoriteDessert: '',
    eatAnytime: '',
    dislikedFood: '',
    allergiesOrAvoid: '',
  },
  habits: {
    chronotype: '',
    wakeTime: '',
    sleepTime: '',
    whenStressed: '',
    whenSad: '',
    whatCalms: '',
    callsOrText: '',
    talkFrequency: '',
    togetherVsSpace: '',
    habitToUnderstand: '',
    annoysQuickly: '',
    makesFeelLovedHabit: '',
  },
  relationship: {
    loveLanguage: '',
    feelAppreciated: '',
    likeSurprises: '',
    likeGifts: '',
    likeNotes: '',
    likeLongCalls: '',
    likeDates: '',
    idealDate: '',
    feelSpecial: '',
    neverForget: '',
    whenUpset: [],
    makesFeelLoved: [],
    partnerShouldRemember: '',
  },
  importantDates: [],
  likesDislikes: {
    favoriteMovie: '',
    favoriteSeries: '',
    favoriteSong: '',
    favoriteSinger: '',
    favoriteActor: '',
    favoriteActress: '',
    favoriteBook: '',
    favoriteHobby: '',
    favoriteGame: '',
    favoriteSocialMedia: '',
    dislikedFoods: '',
    annoysMe: '',
    hateBeingTold: '',
    makesUncomfortable: '',
    dontEnjoyDoing: '',
  },
  dreams: {
    biggestDream: '',
    whereToTravel: '',
    careerGoal: '',
    wantToAchieve: '',
    experienceTogether: '',
    dreamVacation: '',
    alwaysWantedToTry: '',
  },
  aboutUs: {
    firstImpression: '',
    favoriteMemory: '',
    favoriteThingAboutUs: '',
    wantToDoTogether: '',
    kindOfDates: '',
    visitTogether: '',
    memoryToCreate: '',
    wishUnderstoodBetter: '',
    promiseWanted: '',
  },
  rapidFire: {
    teaOrCoffee: '',
    callOrText: '',
    beachOrMountains: '',
    sunriseOrSunset: '',
    sweetOrSpicy: '',
    movieOrSeries: '',
    stayHomeOrGoOut: '',
    longDriveOrLongWalk: '',
    giftsOrQualityTime: '',
  },
  metadata: {
    schemaVersion: '1.0',
    lastUpdated: new Date().toISOString(),
    isCompleted: false,
    currentStep: 1,
    isDemo: false,
  },
};

export const SAMPLE_DEMO_PROFILE: UserProfile = {
  basicDetails: {
    callName: 'Ananya',
    nickname: 'Chinnu / Cookie',
    favoriteColor: 'Lavender & Warm Peach',
    favoriteFlower: 'Baby’s Breath and White Lilies',
    favoriteAnimal: 'Golden Retrievers & Baby Pandas',
    favoriteSeason: 'Mild Rainy Autumn',
    favoritePlace: 'A quiet balcony garden with fairy lights',
    instantHappy: 'A warm hazelnut latte, forehead kisses, and when you send me cute animal reels when I wake up.',
  },
  foodPreferences: {
    favoriteFood: 'Truffle Mushroom Pasta & Crispy Dosa',
    favoriteIndianFood: 'Paneer Butter Masala with garlic naan',
    favoriteSouthIndianFood: 'Crispy Ghee Roast Masala Dosa with coconut chutney',
    favoriteSnack: 'Peri-peri French fries & salted caramel popcorn',
    favoriteChocolate: 'Ferrero Rocher & Lindt Sea Salt Dark Chocolate',
    favoriteIceCream: 'Belgian Chocolate Hazelnut',
    favoriteFruit: 'Fresh Sweet Strawberries & Alphonso Mango',
    favoriteDrink: 'Iced Matcha Latte / Peach Iced Tea',
    favoriteFastFood: 'Crispy thin crust woodfired pizza',
    favoriteRestaurant: 'Little cozy Italian trattorias & rooftop cafes',
    favoriteDessert: 'Warm fudgy brownie with vanilla bean gelato',
    eatAnytime: 'Comforting home-style curd rice or warm soup',
    dislikedFood: 'Bitter gourd and anything with raw coriander overload',
    allergiesOrAvoid: 'Mild lactose sensitivity (oat milk is always preferred!)',
  },
  habits: {
    chronotype: 'Night Owl 🌙',
    wakeTime: '8:30 AM',
    sleepTime: '1:00 AM',
    whenStressed: 'I tend to get quiet and pace around or need to put on noise-cancelling headphones.',
    whenSad: 'Wrap me in a soft blanket, bring something sweet, and just hold me without asking 20 questions right away.',
    whatCalms: 'Soft instrumental lo-fi music, rain sounds, and head scratches.',
    callsOrText: 'Texts throughout the day, one long cozy bedtime phone call.',
    talkFrequency: 'Checking in 2-3 times during the day is sweet; quality over quantity.',
    togetherVsSpace: 'A healthy balance — I love spending whole afternoons together, but also need 1-2 hours of quiet reading.',
    habitToUnderstand: 'When I say "I’m fine" in a low voice, I’m actually overthinking and need a warm hug.',
    annoysQuickly: 'Interrupting while I’m speaking, or being chronically late without texting.',
    makesFeelLovedHabit: 'Remembering small details I casually mentioned weeks ago.',
  },
  relationship: {
    loveLanguage: 'Words of Affirmation & Quality Time',
    feelAppreciated: 'When you notice the little efforts I make and say a genuine "Thank you, I appreciate you".',
    likeSurprises: 'Yes! Small thoughtful surprises like my favorite pastry or a planned spontaneous drive.',
    likeGifts: 'Yes, especially meaningful things with a personal story or note rather than expensive generic items.',
    likeNotes: 'I treasure handwritten letters and will keep them in a special keepsake box forever.',
    likeLongCalls: 'Yes, late night chats where we talk about life, childhood memories, and dreams.',
    likeDates: 'Absolutely, getting dressed up together is magical.',
    idealDate: 'A sunset picnic overlooking city lights or a quiet beach walk followed by dessert tasting.',
    feelSpecial: 'When you look at me across a crowded room and smile just at me.',
    neverForget: 'My soft heart underneath my independent exterior.',
    whenUpset: ['Give me a hug', 'Listen to me', 'Reassure me'],
    makesFeelLoved: ['Quality Time ❤️', 'Words of Affirmation 💬', 'Physical Affection 🤗'],
    partnerShouldRemember: 'Patience and gentle words heal me 100x faster than trying to win an argument.',
  },
  importantDates: [
    {
      id: 'date-1',
      date: '2024-11-14',
      eventName: 'Her Birthday 🎂',
      whyImportant: 'The day the love of my life was born into this world.',
      reminderNote: 'Order lilies and plan a peaceful dinner under the stars.',
      category: 'Birthday 🎂',
    },
    {
      id: 'date-2',
      date: '2023-09-22',
      eventName: 'Our First Official Date ❤️',
      whyImportant: 'The rainy evening at that quaint bookstore cafe where we lost track of time.',
      reminderNote: 'Revisit our cafe spot or write her a sweet letter commemorating the day.',
      category: 'Anniversary ❤️',
    },
    {
      id: 'date-3',
      date: '2025-05-18',
      eventName: 'Her Master’s Degree Convocation 🎓',
      whyImportant: 'A huge academic milestone she worked tirelessly for.',
      reminderNote: 'Bring the biggest celebratory bouquet and take timeless photos.',
      category: 'College 🎓',
    },
  ],
  likesDislikes: {
    favoriteMovie: 'Before Sunrise & About Time',
    favoriteSeries: 'Gilmore Girls & Fleabag',
    favoriteSong: 'Lover by Taylor Swift / Yellow by Coldplay',
    favoriteSinger: 'Taylor Swift, Prateek Kuhad, Gracie Abrams',
    favoriteActor: 'Cillian Murphy & Timothée Chalamet',
    favoriteActress: 'Anne Hathaway & Florence Pugh',
    favoriteBook: 'The Little Prince & Normal People',
    favoriteHobby: 'Pottery, journaling, reading, and film photography',
    favoriteGame: 'Wordle, Codenames, and Mario Kart',
    favoriteSocialMedia: 'Pinterest aesthetics and Instagram foodie reels',
    dislikedFoods: 'Extremely bitter or greasy oily street items',
    annoysMe: 'Leaving wet towels on the bed and forgetting promises',
    hateBeingTold: '"You are overreacting" or "Calm down"',
    makesUncomfortable: 'Sudden loud shouting and aggressive arguments',
    dontEnjoyDoing: 'Rushing in the early morning without breakfast',
  },
  dreams: {
    biggestDream: 'Building a peaceful, cozy home filled with books, art, sunlight, and genuine laughter with the person I love.',
    whereToTravel: 'Amalfi Coast in Italy, Kyoto in cherry blossom season, and Switzerland in winter.',
    careerGoal: 'Leading creative design initiatives and publishing my own illustrated book.',
    wantToAchieve: 'Financial freedom and mastering the art of peaceful slow living.',
    experienceTogether: 'Watching the Northern Lights from a glass igloo while drinking hot cocoa.',
    dreamVacation: 'A 2-week road trip along coastal Europe with zero hurried itineraries.',
    alwaysWantedToTry: 'Scuba diving in coral reefs and taking a professional pasta-making workshop in Florence.',
  },
  aboutUs: {
    firstImpression: 'You had a warm, genuine smile and were surprisingly attentive to what I was saying.',
    favoriteMemory: 'Getting caught in sudden rain while walking back to the car and laughing uncontrollably under a small umbrella.',
    favoriteThingAboutUs: 'How safe and comfortable we feel with each other — we can be goofy or completely silent together.',
    wantToDoTogether: 'Cooking an elaborate three-course weekend dinner from scratch together.',
    kindOfDates: 'Strolling through old bookstores, museum visits, and quiet late-night gelato runs.',
    visitTogether: 'A quiet mountain cabin in Himachal or lake Como.',
    memoryToCreate: 'Dancing together in our living room with our favorite song playing on vinyl.',
    wishUnderstoodBetter: 'That when I get anxious, it is not directed at you; I just need gentle reassurance.',
    promiseWanted: 'To always communicate honestly with kindness, even when things get difficult.',
  },
  rapidFire: {
    teaOrCoffee: 'Coffee ☕',
    callOrText: 'Call 📞',
    beachOrMountains: 'Mountains 🏔️',
    sunriseOrSunset: 'Sunset 🌇',
    sweetOrSpicy: 'Sweet 🍫',
    movieOrSeries: 'Series 📺',
    stayHomeOrGoOut: 'Stay Home 🏠',
    longDriveOrLongWalk: 'Long Drive 🚗',
    giftsOrQualityTime: 'Quality Time ❤️',
  },
  metadata: {
    schemaVersion: '1.0',
    lastUpdated: new Date().toISOString(),
    isCompleted: true,
    currentStep: 9,
    isDemo: true,
  },
};
